arghadipmanna101/Flipkart_Clone

Navabar.html, index.css
I have solved the issue #5 
Please suggest me if further improvement is required.
=> adding hover effect on icons at top

FPZ.html, Navabar.html, index.css, index.html, order.html
fix issues 
#1 #10 #7 
add some new pages 
1. order page 
2. flipkart plus zone 
add links in footer 
add options in nav bar
=> add some additional chnges 

Navabar.html, index.css
Fixes **issue** #22 
Fixed **search bar outline,** and also fixed css on hover of become seller and profile buttons
=> Search bar outline fixed

signin.css, signin.html, signup.css, signup.html
I've adjusted the login and signup pages by making changes in its styling and centered them and adjusted the width to add more breathing space to the page
=> adjusted sign in and sign up pages

Product.html, product.css
I've added the styling to the cards and adjusted to exactly fit the conatiner div and made it look proper by adjusting filter width
=> adjusted the styling of the card in products section

carousel.html, index.html
issue: #25  
I made the changes in the swiper which is not working and also made the swiper to autoplay
=> Added the autoplay swiperjs

index.css
fix the nav bar issue and search bar icon
#37  issue no
=> fix navbar search icon 

Navabar.html, index.css
Thank U @arghadipmanna101 for assigning me this issue. **#17** 
I have successfully added the logo and give it a perfect place.
I also have issue over Navbar correction, so I'll further do changes in that issue
I may put this logo in those issues as well, please consider it :)
=> Added Logo Perfectly

Navabar.html
=> fixing the overlap

signin.html
Updated the page name issue and wrong functionalities between signup and signin page and combined them in a single login page as in actual flipkart
=> signin.html

Navabar.html
updated The dropdown navbar of profile with the actual dropdown navbar of Flipkart
=> Navabar.html

index.css
=> fixed issue #50

Navabar.html, index.css
I have implemented dropdown design similer to Flipkart's sites make the clone correct
Please merge it
=> Add Dropdown Design #56 

package-lock.json, package.json
Hi @arghadipmanna101, I have initialized and added `prettier` npm package.
To format all the files in the codebase all we need to do are these following two commands
`npm install`
`npx prettier --write .`
Issue: https://github.com/arghadipmanna101/Flipkart_Clone/issues/67
=> Added prettier code formatting package

.vscode/settings.json, Navabar.html
=> navbar changed

style.css
#What does this PR do?
This PR adds hover features to icons of  landing page(index.html file.)
Fixes #5
=> Adding hover features to the icons at the top

preloader.html
=> Add a preloader

index.css, index.html
I had improved the footer of the website .
Please review my pull request .
=> Improved the footer of the webpage

index.html
Added slide in from left animation to footer
=> Added animation to footer

README.md
Revised steps to provide comprehensive information, addressing previously incomplete instructions. 
Rectified grammatical errors for improved clarity and readability.
=> Improved explanation to steps and corrected grammatical errors

index.html
Fixed the issue of copy right using JS .
used Javascript to auto update the copyright year
=> fixed copyright_BUG: #261 

index.html
=> fixed the z-index issue in the nav

index.css
@arghadipmanna101 please review this pr to fix the responsive issue of Index.html
https://github.com/arghadipmanna101/Flipkart_Clone/assets/139672976/bb6b9fc6-fff4-40be-9e8d-684bacf6c665
=> fixed footer responsive issue

signup.css
created signup.css for signup.html file styling from scratch . Thankyou
=> Created signup.css

signin.html
created signin.html file from scratch
=> Created signin.html

Navabar.html, index.css, index.html
#232 added.
The description about flipkart is added which looks same as the Original site which contains what to buy, where to buy, how to buy, where to pay and details about the mode of payment.
=> Added description about Flipkart

index.html, manifest.json, sw.js
Added manifest.json <br>
Added sw.js (Service Worker)
please consider this under the label GSSOC 24
=> Added Progressive Web App Support

index.css
#371 fixed.
Updated the index.css file. The styles have been updated and now the whole website is responsive with the help of media queries.
=> Website responsiveness

index.js, profile.css, profile.html
@arghadipmanna101 Sir, i have solved issue regarding profile page plz look at it once.
=> <Added-profile-page>

Navabar.html, Navbar.css
Fixed overlapping problem of dark mode icon
=> Fixed dark mode overlap Issue no.  #415

Navabar.html, index.css, style.css
Hello @arghadipmanna101 
Fixed issue number #417  
I have some added hover effect to make it beautiful and some gap between the navbar components
=> Fixed nav bar hover  issue #417

Navabar.html, index.css, style.css
Fixed issue number #405
Fixed the overlapping issue of dark/light icon
=> Fixed the overlapping issue of dark/light icon ! #405

index.css, index.html
Added back to top button on the website
=> Added back to top button

signin.css
Have created signin.css file from scratch, for Already present file signin.html (Also created by me)
@arghadipmanna101 I request you to please merge this as without css , signin.html file is looking ugly 
to the issue #131 
Have created Pr already related to this issue but it  doesnt merge till now , So I have created this new Pr . Thankyou
#254 , #337
=> Created signin.css

FPZ.html, index.html
I have added the header, content page and the footer to the flipkart plus page.. #152 is resolved by this PR..
@arghadipmanna101  Mark it under GSSoC'24
=> Created Flipkart plus page

Navbar.css, categorylist.css, index.css
Reduce The overlapping between Content.
Add hover effect on every image when the user hover the image it increase their size little bit by transition effect. Also Update the navtabs with better design.
=> Update the Navtabs with Hover effect

index.css, index.html
Solved issue #379 
Theme is properly applied in footer section.
=> Theme change in footer

Navabar.html
@arghadipmanna101  Fixed issue #522 
Before : 
After : 
Please don't forget to add labels : gssoc and level2
=> Fixed repitition of icons

profile.css, profile.html
Issue no: #347 
I have successfully updated the profile page.
Please check it once @arghadipmanna101.
=> issue_no_#347 Profile page updated

index.css
=> Task #481 completed

categorylist.css, index.css, index.html
I have added hover effect to all the images present in the website using the transition property
=> Added hover effect to all the images

CONTRIBUITING.md
Fully new CONTRIBUITING.md file for our project . Thankyou 
This PR is for the issue #484
Please find the screenshots of the preview of this file attached
=> Created CONTRIBUITING.md file from scratch

index.css
I justified the text from both the sides in all the sections containing content .
Before
After
=> Text will be justified in all content sections .

index.html
Added chat bot which assist user Fixed Issue #532
=> Added Chat Bot (GSSoC'24)

Navabar.html
Updated options section .
closes issue #349
=> Updated Navabar.html

index.css
Fixed the issue #574 
Hello PA, I have made the necessary changes properly.
=> changed margin

img-add1.html, img-add2.html, img-add3.html, index.html
images which are displaying at top now they will open in new tab 
fix issue #377
=> display image responsive

Navabar.html, faq.css, helpcentre.css, helpcentre.html, index.html
@arghadipmanna101 plz merge this issue and also merge my previous issue of FAQ section under gssoc24 label
=> Added 24*7 customer care helpline page

Navabar.html
I have design a new navbar for better look and also by tomorrow I will add new pages for each category
=> Update navbar add new pages

index.css, style.css
Issue #569 
The text on the homepage was not on the mark 
I have successfully changes it, which makes the webpage much more attractive and professional just like flipkart official website
=> corrected text on Homepage 

index.css
I fixed the overlapping of mode changing and the download button .
closes : #537
=> Fixed Overlapping of download and mode changing button .

signin.css, signin.html
included the feature forgot password on the sign-in page. which fixes #474
=> Added Forgot Password

profile.html
The existing logo was colliding with the profile form 
Now it is repositioned from the profile form.
=> flipkart logo is repositioned since it was collided with the form

Navabar.html, gift.js, giftcard.css, giftcard.html
#557 added.
The gift card page is added with the navigation bar and footer section which is also responsive.
It displays the amount to be gifted to the person.
After clicking on the BUY button, it displays 'you have selected an amount of Rs. X'.
=> #557 Added Gift Card Page

index.css, style.css
I made the website responsive so that it looks good on all kinds devices, with screen large or small. 
Here is how I verified the changes made:
https://github.com/arghadipmanna101/Flipkart_Clone/assets/162856568/3dcf5e74-3beb-43aa-b955-297575005694
https://github.com/arghadipmanna101/Flipkart_Clone/assets/162856568/3fb04a2a-c182-49a2-adb9-13ca588e9aee
=> Made website responsive

index.html
Hi @arghadipmanna101 
I have changed twitter logo in the web page.
=> twitter x logo added

cart/cart.html
fixes #684 
before:
after : 
@arghadipmanna101 please label this issue under gssoc
=> fixes BUG :  title of cart page

Navabar.html, index.html, profile.html, wishlist.css, wishlist.html
Hi @arghadipmanna101 
I have Fixed issue #581 and added the wishlist page to the Flipcart clone
**Screenrecord:**
https://github.com/arghadipmanna101/Flipkart_Clone/assets/101971980/8223e03b-a3a8-49e8-b662-90a3941fcb46
Please take a look at it and review it.
=> Added "Wishlist" Page Feature

index.css, index.html
Hello @arghadipmanna101,
#619 isuue is solved
-The heading of that section clearly visible without hiding
-The Corner product images are aligned properly
- [X ] Bug fix
Before:
After:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> closes #619 Deals section heading and corner products visible clearly

Navabar.html, Navbar.css
Closes issue #625 
Previously, in dark mode the nav icons were not at all visible and the nav items were not aligned properly!
(DARK MODE)
(LIGHT MODE)
=> Navbar dark mode issue resolved

profile.css, profile.html
I have contribute under GSSoC'24
Fixes #602 
There was a bug in your website that the profile page was not responsive , i have fixed that issue by chnaging the profile.html and profile.css .
This is the screenshot where you can see that the profile page is fully responsive and working
The website is looking good when the big is fixed.
=> Profile page is fully responsive

LEARN.md
created lean.md file from scratch
closes #595 
created file from scratch
=> Created LEARN.md

Gift Card/GiftCard.css, Gift Card/GiftCard.html, Navabar.html, index.html
This PR introduces a new Gift Card page to our application. The Gift Card page allows users to purchase, send, and redeem gift cards. The page includes various features such as selecting gift card amounts, personalizing messages, and tracking gift card balances.
Fixes #612
https://github.com/arghadipmanna101/Flipkart_Clone/assets/66481063/76cb47e8-f062-4e25-bca1-15461c7e8ce2
-  Go to Homepage
-  Go to Profile Section in Navigation 
-  Go to Gift Cart
=> feat: Added Gift Card Page

index.css, index.html
fixes #799 
I have fixed size and alignment of social icons in the footer section and changed the color of the footer section as per the original website .
=> alignment of social icon and change of footer color

index.html
=> Issue #674 fixed; Compliance spelling error fixed

Navabar.html, Navbar.css
Solved the navbar problem as per the issue #727
Now the navbar is properly visible in responsive view. I have made changes particularly in the CSS . I have also updated other styling such as hover effect in the navbar.
Besides updating the navbar for responsive view , I have also updated the hover effects of the navbar items.
=> Updated navbar for responsive design

index.html, pages/contact_us/contact_us.css, pages/contact_us/contact_us.html
Create a Responsive Contact Us Page
(plz give me labels)
=> Add contact us page

content-page.html, index.html
BUG: misaligned CSS causing visually unappealing and informal blue highlight on hover on items of product showcase carousel and links of footer section #855
BUG #855 Resolved : Replaced blue highlight on hover with white from product showcase carousel and links of footer section
There was some misaligned CSS which was causing visually unappealing and informal blue highlight on hover on items of product showcase carousel and links of footer section, I have improved and tested it on my local system,and  I would like to merge the changes.
The UI changes I am proposing to make, adhere to the design of components present in the original Flipkart website.
Before Bug Resolution :
After Bug Resolution :
@arghadipmanna101 please don't forget to assign this to me, also add the required labels, …
=> BUG #855 Resolved : Replaced blue highlight on hover with white from product showcase carousel and links of footer section

faq.css, index.html
=> Updated FAQs

index.css, index.html
#793 
Enhanced the "Other Top Deals" section with a responsive grid layout, ensuring seamless user experience on diverse devices. Incorporated engaging hover effects and refined styling to elevate the visibility and interactivity of "Show Items" buttons, thus improving overall user engagement and satisfaction. Additionally, optimized the section's layout for better visibility and interaction across various devices.
Before
After (Rounded corners and when cursor on picture you will see the show more button on any image in other deals)
Enhanced the "Other Top Deals" section with a responsive grid layout, ensuring seamless user experience on diverse devices. Incorporated engaging hover effects and refined styling to elevate the visibility and interactivity of "Show Items" buttons, thus …
=> Added Responsive Image Grid with 'Show Items' Button and Rounded Corners - Modified 

cart/cart.css, cart/cart.html
Fixes issue #718 
Changed the logo and added styling, now the flipkart text is visible in cart page navbar. 
Before changes:
After changes:
Please check the PR and let me know if any changes to be made. Thank you.
=> Flipkart text is now visible in cart page navbar.

FPZ.html, electronics.html
#783 
Added hover effect to the mobile category which is there in the FPZ page. This would make the page more creative and responsible.
- [ X] Bug fix
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- Closes #783
=> Hover effect for mobile category added

electronics.html
None
The Hover effect is added for electronics page which will make the page more creative and responsible. This is the Unique hover effect.
- [X ] Bug fix
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- Closes #739
=> hover effect added for electronics page

cart/cart.css, cart/cart.html
#634 
Added dropdown menu to login button in cart page.
=> Added dropdown menu in login button

Learn.md, index.css, index.html
Fixes #697 
Screenshot of the footer
=> corrected the alignment of the footer on home page

index.html
Collapse feature in FAQ section.
The answer to the FAQ was unable to drop down when clicked on. I added the collapse feature to the FAQ and also added an icon for the down arrow to make it user friendly. This is wrt issue #708 
@arghadipmanna101 Kindly review the PR and accept it to incorporate the changes.
=> FAQ collapse feature add wrt issue #708

.github/workflows/pr-comment.yml
None
"This PR introduces an automated workflow that comments on every new pull request made to the project. The comment thanks contributors and informs them that their PR will be reviewed soon, ensuring immediate and consistent communication for all contributors."
- [X ] Feature enhancement
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- Closes #671
=> Add workflow to comment on new pull requests

CONTRIBUITING.md
resolves #706 
Added git commands in the contribution guidlines.
- [ x] Documentation update
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
=> Updated CONTRIBUITING.md file

cart/cart.css, cart/cart.html
1. Updated the navbar of the cart page
2. Added footer to the cart page
3. Added styling to footer to make it better
Closes #637 and #638
This PR resolves 2 issues.. #637 and #638 
@arghadipmanna101 Please label PR as it resolves 2 issues.. Please consider it while labelling.. Assign me this PR
=> Updated the navbar of the cart page and the footer of the cart page #637 and #638

signup.css, signup.html
None
This PR enhances the user interface of the page and adds a footer section that includes links to About, Help, and Consumer Policy.
This PR focuses on improving the overall user experience by refining the UI and adding a footer section.This enhancement is part of our ongoing effort to make the interface more user-friendly and accessible.
=> Add footersection and enhances UI of page

README.md
I had corrected the readme.md 6th point in it.
=> Readme corrected the 6th point 

README.md
Hello PA,
I have added the readme information in readme.md file
=> readme info added

Navabar.html, notification.css, notification.html
Added Notification page inside 3 dots under navbar section with toggle buttons which u can toggle on/off ur notification preferences accordingly.
@arghadipmanna101 plz merge this issue no #659 regarding addition of notification page under gssoc24 label.
=> <Added Notification page inside 3 dots under navbar section>

index.html
I added icons in Faq an also made it collapsible on clicking anywhere in the box and not just the text .
=> Made changes in FAQ

signin.html, signup.css
Description
Login with google feature completed and alignment also corrected
Please merge the pull request with gssoc and level 2 tags
=> ISSUE NO: 445 GOOGLE AUTHENTICATION LOGIN COMPLETED

cat_list.css, categorylist.css
UI Feature Enhancement
Padding and Round corners has been added where necessary.
A zoom feature has been incorporated to activate on hover.
=> Improvement in UI (in category list)

.idea/.gitignore, index.html
Fixed Issue #947 
Description
Successfully added brand directory. In PR 947 their was some conflict So, conflict successfully solved.
Before:
After:
- [yes ] Bug fix
- [yes ] Feature enhancement
Checklist:
- [ yes] I have performed a self-review of my code
- [yes ] I have read and followed the Contribution Guidelines.
- [ yes] I have tested the changes thoroughly before submitting this pull request.
- [ yes] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [yes ] I have commented my code, particularly in hard-to-understand areas.
- -[yes] I solved this issue under Gssoc24.
=> Added brand directory.

index.css
Closes #59
1. Added transition to background color
2. Added transition to bgorder
3. Added zoomin and fade in animations
=> Added animations and transitions to the page #59

css/index.css
1. The navbar-brand img is targeted to apply a scale transformation on hover.
2.  The input within the searchbar is targeted to change the border-color on focus.
3. The nav-link img is targeted for a scale transformation on hover.
4. The cartLogoandname img is targeted for a scale transformation on hover.
5. The navItem4 img is targeted for a scale transformation on hover.
6. The moreLinksDropdow .nav-link img is targeted for a scale transformation on hover.
@arghadipmanna101 Please label this PR under GSSoC
=> Improved Hovering Effect #128

.github/workflows/greetings.yml
closes: #1059
added automatic github greeting bot
=> Added github automatic greeting bot

css/footer.css, footer/footer.html
none
I added the Instagram logo to the footer and made the opacity 0.75
- [x ] Feature enhancement
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
please label gssoc and level
=> added logo

css/index.css
issue no #1074
I made scrollbar stylish with blue shades of thumb in scrollbar given them radius to top and bottom.
Also add hover effects on Scrollbar.
It looks amazing on this website.
=> Scrollbar styled

css/homeHeader.css
UI related issue: #813 
There is no hover effect displayed on all of the buttons of the navbar; it is only displayed on the account and menu button
The hover effect has been added to the remaining buttons in the navbar (cart, become a seller). 
close #813
=> add Hover effect in Header (cart, become a seller button)

helpcentre/index.html
<enlarge image of flipkart  which is not working in helpcenter page>
@arghadipmanna101 resolved issue no #1037 plz merge my pr under gssoc24 label
=> <enlarge image of flipkart  which is not working in helpcenter page>

js/bootstrap.bundle.min.js, js/homeHeader.js
Red circle was visible on having zero items.
Red circle is now not visible on having zero items.
https://github.com/arghadipmanna101/Flipkart_Clone/assets/162856568/d610cb55-83b4-49b6-b852-66b263a7479e
=> Improved Add to Cart feature

plus/index.html
Closes #1066 
1. Added transition to bg
2. Increase background size on hover
3. Add a transition effect to the product list
4. Shift slightly on hover
5. Added box shadow to the product
6. Increased box shadow on hover
7. Added transition to product image
8. Product image Zoom slightly on hover
9. Added transition for product name font color
10. Added Blue color to font color on hovering
11. Added Transition to product price
12. Product price color changes on hovering
@arghadipmanna101 Please label this PR under GSSoC
=> added styles to flipkart plus page

css/contactus.css
#1264  solved.
#1264 
Feat: Contact Us section UI design CSS style improving.
I improved the CSS styling of the UI of Contact section.
I improved the CSS styling of the contact section, Here I add blinking effect to the contact section.
Now it looks good.
Video -
https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/fb06f55f-8fad-4976-acfa-2a5a24ce0b81
=> Feat: Contact Us section UI design CSS style improving.

index.html
Changed some style in the navbar
#1240
Made some changes in the style of the navbar now it looks like original flipkart web
=> updated the navbar style now it's better

addtokart/checkout.html, addtokart/style.css, js/addKartProduct.js, viewcart/index.html
#1130 
Created a checkout page. The buy now button redirects to it
https://github.com/arghadipmanna101/Flipkart_Clone/assets/142666229/ee604021-030e-4aeb-beed-e33cd578b379
GSSoC'24
=> added functionality to buy now button

css/footer.css
issue no #1172 
**Add transitions ,transform added shadow by filter and make it attractive hover effects.**
**When Hover on Facebook Icon**
=> Hover effects added on Social icons

css/index.css, index.html
https://github.com/arghadipmanna101/Flipkart_Clone/assets/142777810/b1532e1e-34f0-4c19-b3fd-29965d286afb
=> fixed issue #1280 : FAQ section

css/footer.css
#1262  solved.
#1262 
Feat: Request to improve hover underline effect and social media icons in the footer section.
I have change the CSS of the footer section and add the nth child hovering effect with color in the social media icons and add text-decoration-size, text- shadow in the h5 tag.
video - 
https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/37c29ef3-2593-4f7f-8662-1021285115bc
=> Improved the text effect and social media icons effect in the foore section.

footer/footer.html
=> Added Privacy Policy Page in flipKart clone

viewcart/viewcart.js
Solved issue #1229
Both the - and + buttons are now working which on click will increase or decrease and display the quantity of an item.
https://github.com/arghadipmanna101/Flipkart_Clone/assets/143121854/9022b6f6-c496-4043-83fd-be3b47e72a0a
When the quantity of an item is remaining 1 then if again - button is clicked then pop up is shown whether to remove item or not.
=> + and - buttons on the my cart page are now working .

index.html
Reverts arghadipmanna101/Flipkart_Clone#1306
=> Revert "enhance header section"

css/index.css, js/categoryData.json
resolves #1223 
- Bug fixed: Spacing between components, and font issue
- Change the category icon images
- Added missing categories
- Fixed font size, alignment, weight
- Improved the category with grid css
- Made the category almost similar to that of original website
=> Category Edited again

viewcart/index.html
#1346
Now action takes place on click at any position in the log in button like an actual button and not only on the middle of the button.
https://github.com/arghadipmanna101/Flipkart_Clone/assets/143121854/eebbf907-3073-4406-8f29-634c51bf0818
=> logbut-commit

footer/footer.html, pages/Licensing/Licensing.css, pages/Licensing/Licensing.html
hey @arghadipmanna101 ,
issue closes #1321 
I have **added a dedicated Licensing Page reflecting MIT License** 
please take a look - 
Please take a look and review it.
=> ✔️ Added a Dedicated Licensing Page!

footer/footer.html, pages/Security/security.css, pages/Security/security.html
=> Created Security Page in Flipkart clone

login/login.html
#1380 
Fixed the bug in #1380 
=> register page linked

css/homeHeader.css, header/header.html, login/login.html
=> Header Fixed

index.html
=> home navbar fixed

css/index.css, index.html
Added scroll to top button with progress bar
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar in the scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.
Fixes issue : #1316 
GSSOC'24
=> Added scroll to top button with progress bar

css/index.css, index.html
Solved issue #1307 
- [√ ] Bug fix
- [ X] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> ui of home page 

login/login.css, login/login.html
=> new form added

css/index.css
#1393
Now the text in the FAQ is visible
This PR is under GSSoC 2024
=> Solved FAQ text disappearing

addtokart/style.css, js/addKartProduct.js
closes #1225 
- Fixed font sizes
- Added icons in front of bank offers
- T&C , "View more", "View X more"
- Added question mark(info) icons where necessary
- Added Check delivery by pincode section
- Added warranty section
- Button colours, height, width fixed
- alignments fixed
- Overall Page's Frontend/UI improved
=> Product Description Page Improved

css/login-signup.css
#1344
Fixed the overflow of input field and button on login page in responsive view. Now these do not overlap for various smaller devices .
=> Fixed the overflow of input field and button on login page in responsive view.

index.html
Added Drop Down With more Help Links
Added Drop Down With more Help Links
=> Added Drop Down With more Help Links

feedback/feedback.html
#1429 
Added a feedback form UI included star marking rating system also in it.
=> feedback form added

account/login-signup.html, js/login-signup.js, plus/index.html, server_backend/.env, server_backend/models/User.js, server_backend/package.json, server_backend/routes/auth.js
=> Slideshow Carousel added

account/login-signup.html, addtokart/checkout.html, footer/footer.html, index.html, pages/privacypolicy/index.html, pages/privacypolicy/styles.css
#1439 
Built the whole privacy policy page and link it to the whole site.
=> privacy policy page built

pages/terms/index.html, pages/terms/styles.css
=> Terms of uses added

addtokart/checkout.html, dashboard/userdashboard.html
=> checkout page fixed and new ui added

css/index.css
Fixes #1417 
- Made the Home page fully responsive for mobile-view.
- Now the home page will look good in mobile view also.
https://github.com/user-attachments/assets/f65979be-8f90-40e4-91d3-d573e7f0b983
_Please review and merge this pull-request under GSSoC'24_
=> Made the Home page responsive

header/header.html
Solves #1408
Dropdown options are now visible on hover of more link of the navbar . I have also added animations and transitions on hover of the dropdown items .
https://github.com/user-attachments/assets/4e081b8a-29a9-4c4b-a2dc-cd251ac76e84
=> Modified the dropdown of more link on the navbar of login/signup page .

plus/index.html, plus/plus.js, plus/products.json
#1466 
Added `json` styled fetching and added the plus page with products too. Here are the changes and page made.
=> plus page added

sell-online/index.html, sell-online/script.js, sell-online/styles.css
=> seller form added

css/index.css, index.html
hey @arghadipmanna101 
issue closes #1448 
I have updated the FAQ Page Completely.
Please take a look - 
https://github.com/user-attachments/assets/ea2cd3a7-c07d-4fb5-bc1f-7afeb3b1ba79
=> ✔️Improved the FAQ Section of the Website!

index.html
Fixes #1461 
- Fixed the dropdown style of the navbar in home page.
- Now the dropdown menu will look good and will be easy to use.
_Please review and merge this pull-request under GSSoC'24_
=> Fixed the dropdown menu of navbar in home page

index.html, offerpage/offerportal.html, pages/EPR_Page/epr.html, pages/Licensing/Licensing.html, pages/Security/security.html, pages/Sell_Online/sell_online.html, pages/contact_us/contact_us.html, pages/content-page.html, pages/privacypolicy/index.html, pages/terms/index.html, plus/index.html, sell-online/index.html, the-gift-card-store/index.html, viewcart/index.html
Hey @arghadipmanna101 
issue closes #1447 
I Have implemented the Scroll Indicator Progress bar in **ALL the existing pages in the website.**
Please take look..
https://github.com/user-attachments/assets/df8a405b-fc2e-48da-a9d7-f3b09df6d2f6
=> ✔️Implemented Progress Scroll Indicator bar in ALL Pages!

css/contact.css, css/contactus.css, index.html
fixed: #1425 
reduced the size of submit button
=> reduced the size of  submit button

css/contact.css, css/contactus.css, index.html
closes: #1423
changed the contact form div position aligned it correctly
=> changed the position of the contact form div 

index.html
#1443
Enhanced the current navigation bar by adding a smooth and visually appealing hovering effect to the navbar links. Also aligned the navbar links.
=> Navbar Enhanced and hovering effect added

index.html
closes #1518 
@arghadipmanna101 please see this PR for the concerned issue mentioned.
=> button fixed

dashboard/sellerdashboard.html
closes #1523 
@arghadipmanna101 please review this pr asap.
=> Seller dashboard added

index.html
=> ui updated

account/notifications.html, account/rewards.html, components/footer.html, footer/footer.html, helpcenter.html, index.html, the-gift-card-store/index.html
#1531 
@arghadipmanna101 please review this pr.
=> added the gift store page

sell-online/index.html
Fixes #1528 page
Fixed Bug
@arghadipmanna101 view this PR
=> Fix Sell Online Page

css/homeHeader.css, index.html
This fixed the dropdown section 
=> Fixed dropdown to look similar to flipkart website

index.html
#1526
- Made the contact us form responsive for mobile view.
- Now the form will look good in mobile view as well.
https://github.com/user-attachments/assets/9d5a63ed-1701-4347-ae9a-cb5505c8265d
@arghadipmanna101 sir please review & merge my pull-request under GSSoC'24
=> fix: Made the contact us form responsive

footer/footer.html, pages/help center/index.html, pages/help center/styles.css
Added 24x7 Customer Help Center Page
@arghadipmanna101 Please review and merge this PR as soon as possible.
Completed #1536
=> Added 24x7 Customer Help Center Page

account/orders.html, index.html
closes #1578 
@arghadipmanna101 please review and merge this PR asap.
=> UI updated and styling fixed

src/Electronics/footer_.css, src/Electronics/index.html, src/Electronics/thisComponet.js
=> updated Electronics

src/Furniture/footer_.css, src/Furniture/index.html, src/Furniture/thisComponet.js
=> furniture updated

src/Fashion/footer_.css, src/Fashion/index.html, src/Fashion/thisComponet.js
=> Fashion updated

src/Grocery/footer_.css, src/Grocery/index.html, src/Grocery/thisComponet.js
=> updated grocery

src/Mobiles & Tablets/footer_.css, src/Mobiles & Tablets/index.html, src/Mobiles & Tablets/thisComponet.js
=> updated Mobile store

src/TVs & Appliances/footer_.css, src/TVs & Appliances/index.html, src/TVs & Appliances/thisComponet.js
=> appliances updated

src/Travel/footer_.css, src/Travel/index.html, src/Travel/travel-script.js, src/Travel/travel-style.css
=> updated travel page

src/Two Wheelers/footer_.css, src/Two Wheelers/index.html, src/Two Wheelers/thisComponet.js
=> updated two Wheelers

src/Beauty, Toys & More/footer_.css, src/Beauty, Toys & More/index.html, src/Beauty, Toys & More/thisComponet.js
=> beauty products updated

css/categories.css, css/index.css, index.html
Closes #128 
1. Adeed Hover effects for Category Grid
2. Added smooth transition
3. Added smooth transitions to buttons
4. Added Hovering effect for dropdown
5. Added transition for best for you section
6. Added hovering effect for s1 section
7. Added hoverin effect for Select our Choice section
8. Added transition to category grid
9. Hover effect for Best Deal for You section 
10. Hover effect for Shop Now Under 500 Rs section 
11. Hover effect for Top Selection section
12. Hover effect for Mobile Phone Under 15000 Rs section 
13. Hover effect for Suggested for You section 
@arghadipmanna101 I am an active GSSOC Contributor. Please merge this PR under GSSOC
=> Impoved hovering effects of the page #128

Learn.md
close #346 
Added a Learn.md file .
=> Added Learn.md file

TermsOfUse.html
Hey @arghadipmanna101 
- fixes  #1529
I have designed and created a Terms of Use Page for Flipcart clone 
Please take a look and merge this PR
=> ✨ Feat: Design a Terms of Use Page for Flipcart clone 
